# -*- coding: utf-8 -*-
"""project_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FVuK9bRr5v9cdiy-JP7bOGZVjVjijuKZ
"""

import streamlit as st
import joblib
import pandas as pd

# Load the saved models
model_super = joblib.load('prophet_model_super.pkl')
model_diesel = joblib.load('prophet_model_diesel.pkl')
model_kerosene = joblib.load('prophet_model_kerosene.pkl')

# Streamlit app layout
st.title('EPRA Fuel Predictor')

# Modified date selection widget for date range
selected_date_range = st.date_input("Select a date range for fuel price prediction:", [])

# Ensure the selected date range is appropriate
if selected_date_range:
    start_date, end_date = selected_date_range
    # Add your logic here to adjust start_date and end_date if needed

    # Function to make predictions
    def make_prediction(model, future_date):
        future_df = pd.DataFrame({'ds': [future_date]})
        forecast = model.predict(future_df)
        return forecast['yhat'].iloc[0]

    # Display predictions for the range
    if st.button('Predict Prices'):
        date = start_date
        while date <= end_date:
            price_super = make_prediction(model_super, date)
            price_diesel = make_prediction(model_diesel, date)
            price_kerosene = make_prediction(model_kerosene, date)

            st.write(f"Predicted Super Price on {date}: {price_super:.2f}")
            st.write(f"Predicted Diesel Price on {date}: {price_diesel:.2f}")
            st.write(f"Predicted Kerosene Price on {date}: {price_kerosene:.2f}")
            date += pd.Timedelta(days=1)